<?php
/*
 * Language File: zh_TC, 繁體中文
 * For Taiwan Province, HongKong Special Administrative Region and Macau Special Administrative Region of People's Republic of China.
 * Also for some overseas regions.
 * Translate by bobwxc (bobwxc@yeah.net) 2020
 */

$lang = array();

$lang['banned']         = "你已經被 " . $site_name . "屏蔽。";
$lang['expired']		= "您要查找的粘貼已過期";
$lang['guestwelcome']	= $site_name . " 允許您提交文本和代碼。";
$lang['pleaseregister'] = "<br /><br /> <a class=\"btn btn-default\" data-target=\"#signin\" data-toggle=\"modal\" href=\"#\">登錄</a> 或 <a class=\"btn btn-default\" data-target=\"#signup\" data-toggle=\"modal\" href=\"#\">註冊</a> 來提交新粘貼。此乃免費！";
$lang['registertoedit'] = "<a class=\"btn btn-default\" data-target=\"#signin\" data-toggle=\"modal\" href=\"#\">登錄</a> 或 <a class=\"btn btn-default\" data-target=\"#signup\" data-toggle=\"modal\" href=\"#\">註冊</a> 以編輯粘貼或創建分叉。皆為免費！";
$lang['editpaste']		= "編輯";
$lang['forkpaste']		= "創建分叉";
$lang['guestmsgtitle']	= $site_name . " 用於源代碼或Debug調試文本等。";
$lang['guestmsgbody']	= "<a data-target=\"#signin\" data-toggle=\"modal\" href=\"#\">登錄</a> 或 <a data-target=\"#signup\" data-toggle=\"modal\" href=\"#\">註冊</a> 以編輯、刪除和跟蹤您的粘貼。";
$lang['emptypastebin']	= "沒有要顯示的粘貼。";
$lang['siteprivate']	= "此粘貼為私有。";
$lang['image_wrong']    = "驗證碼錯誤！";
$lang['missing-input-response']   = "缺少reCAPTCHA response參數，請驗證設置。";
$lang['missing-input-secret']     = "reCAPTCHA secret參數丟失，請將其添加到設置中。";
$lang['missing-input-response']   = "reCAPTCHA response參數無效，請重新填寫。";
$lang['invalid-input-secret']     = "reCAPTCHA secret參數無效或格式錯誤，請重新檢查粘貼設置。";
$lang['empty_paste']	= "您不能提交空的粘貼。";
$lang['large_paste']	= "您的粘貼超過容量限制，最大容量為 " . $pastelimit . "MB";
$lang['paste_db_error'] = "無法提交到數據庫。";
$lang['error']          = "出現了一些問題:(";
$lang['archive']        = "存檔粘貼";
$lang['contact']        = "聯絡我們";
$lang['full_name']      = "請填寫您的全名。";
$lang['email']          = "請填寫有效的電子郵件地址。";
$lang['email_invalid']  = "電子郵件地址無效！";
$lang['message']        = "請填寫您的資料。";
$lang['login/register'] = "登錄/註冊";
$lang['rememberme']		= "記住登錄狀態";
$lang['mail_acc_con']   = "$site_name 帳戶認證";
$lang['mail_suc']       = "驗證碼已成功發送到您的電子郵箱。";
$lang['email_ver']      = "電子郵箱已驗證。";
$lang['email_not']      = "找不到電子郵件地址。";
$lang['pass_change']    = "密碼更改成功併發送到您的電子郵箱。";
$lang['notverified']	= "帳戶未驗證。";
$lang['incorrect']		= "用戶名/密碼錯誤！";
$lang['missingfields']	= "必須填寫所有字段。";
$lang['userexists']     = "用戶名已被佔用！";
$lang['emailexists']	= "電子郵件已註冊！";
$lang['registered']		= "帳戶註冊成功。";
$lang['usrinvalid']		= "您的用戶名只能包含字母和數字。";
$lang['mypastes']		= "我的粘貼";
$lang['pastedeleted']	= "粘貼已刪除。";
$lang['databaseerror']	= "無法提交到數據庫。";
$lang['userchanged']	= "用戶名已更改。";
$lang['usernotvalid']	= "用戶名不可用。";
$lang['privatepaste']	= "這是私有粘貼。";
$lang['wrongpassword']	= '密碼錯誤！';
$lang['pwdprotected']	= '密碼保護的粘貼';
$lang['notfound']		= "未找到";
$lang['wrongpwd']		= "密碼錯誤，請重試！";
$lang['myprofile']		= "個人資料";
$lang['profileerror']	= "無法更新配置信息 ";
$lang['profileupdated']	= "您的個人資料已更新 ";
$lang['oldpasswrong']	= "原密碼錯誤！";
$lang['archives']		= "粘貼存檔";
$lang['archivestitle']  = "此頁包含最新創建的100個公開粘貼。";
$lang['pastetitle']		= "粘貼標題";
$lang['pastetime']		= "時間";
$lang['pastesyntax']	= "高亮語法";
$lang['pasteviews']		= "粘貼視圖";
$lang['wentwrong']		= "出現了一些問題:(";
$lang['versent']		= "驗證電子郵件已發送到您的電子郵箱。";
$lang['modpaste']		= "修改粘貼";
$lang['newpaste']		= "新建粘貼";
$lang['highlighting']	= "語法高亮";
$lang['expiration']		= "粘貼有效期";
$lang['visibility']		= "粘貼可見性";
$lang['pwopt']			= "查看密碼（可選）";
$lang['encrypt']		= "在數據庫中加密";
$lang['entercode']		= "輸入驗證碼";
$lang['almostthere']	= "即將成功，一步之遙。";
$lang['username']		= "用戶名";
$lang['autogen']		= "自動生成的用戶名";
$lang['setuser']		= "設置您的用戶名";
$lang['keepuser']		= "保留自動生成的用戶名";
$lang['enterpwd']		= "輸入密碼";
$lang['totalpastes']	= "所有粘貼：";
$lang['membtype']		= "會員資格類型：";
$lang['email']			= "電子郵件";
$lang['fullname']		= "全名";
$lang['chgpwd']			= "修改密碼";
$lang['curpwd']			= "當前密碼";
$lang['newpwd']			= "新密碼";
$lang['confpwd']		= "確認新密碼";
$lang['mypastes']		= "我的粘貼";
$lang['viewpastes']		= "查看我的所有粘貼";
$lang['recentpastes']	= "近期粘貼";
$lang['user_public_pastes'] = "的粘貼";
$lang['yourpastes']		= "您的粘貼";
$lang['mypastestitle']	= "所有粘貼，一處呈現。";
$lang['delete']			= "刪除";
$lang['highlighted']	= "文本已選擇, 用 Ctrl+C 快捷鍵來複製到您的剪貼板。(蘋果Mac OS使用 &#8984;+C )";
$lang['newpaste']		= "新建粘貼";
$lang['download']		= "下載";
$lang['showlineno']		= "顯示/隱藏行號";
$lang['copyto']			= "複製到剪貼板";
$lang['rawpaste']		= "原始文本";
$lang['membersince']    = "加入：";
$lang['delete_error_invalid'] = "不能刪除粘貼，因為它不存在或非您所擁有。";
$lang['not_logged_in']  = "您必須登錄才能執行此操作。";
$lang['public']         = "公開";
$lang['unlisted']       = "不列出";
$lang['private']        = "私有";
$lang['hello']			= "您好";
$lang['profile-message'] = "這是您的個人資料頁，您可以在這裏管理您的粘貼。<br /> 您的所有公開、私有和不列出的粘貼都將顯示在這裏。您也可以從此頁中刪除粘貼。如果其他用戶訪問您的頁面，他們只能看到您的公開粘貼。";
$lang['profile-stats']	= "您的一些統計資料：";
$lang['profile-total-pastes'] = "所有粘貼：";
$lang['profile-total-pub']	= "所有公開粘貼：";
$lang['profile-total-unl']	= "所有不列出粘貼：";
$lang['profile-total-pri']	= "所有私有粘貼：";
$lang['profile-total-views'] = "您的粘貼總覽：";
$lang['embed-hosted-by'] = "持有：";
$lang['view-raw']		= "查看原始文本";
?>