<?php
/*
 * Paste $v3.2 2025/08/21 https://github.com/boxlabss/PASTE
 * demo: https://paste.boxlabs.uk/
 *
 * https://phpaste.sourceforge.io/
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License in LICENCE for more details.
 */
 
$currentversion = 3.2;
$pastelimit = "10"; // MB

// OAuth settings (for signups)
$enablefb  = "no";
$enablegoog= "no";
$enablesmtp= "no";

// Database information
$dbhost     = "localhost";
$dbuser     = "pastedev";
$dbpassword = "duXlUs-aG1cynLvd";
$dbname     = "pastedev";

// Secret key for encryption
$sec_key = "This is generated by /install";
define('SECRET', $sec_key);

// Tidy URLs: set to "1" if your server is configured for mod_rewrite / pretty URLs
$mod_rewrite = "0";

// Code highlighting engine for non-Markdown pastes: 'highlight' or 'geshi'
$highlighter = $highlighter ?? 'highlight'; // new

// Default theme for highlighter.php (see includes/Highlight/styles)
$hl_style = 'hybrid.css';

/**
 * Build the list of selectable formats
 * - When using highlight.php, we get the json language files from includes/Highlight/languages
 * - When using GeSHi, we fall back to the classic list.
 */
$popular_formats = []; // will be set below

if ($highlighter === 'highlight') {
    require_once __DIR__ . '/includes/Highlight/list_languages.php';
    $langs = highlight_supported_languages();

    // Friendly display labels
    $label_map = [
        'cpp'        => 'C++',
        'csharp'     => 'C#',
        'fsharp'     => 'F#',
        'objectivec' => 'Objective-C',
        'plaintext'  => 'Plain Text',
        'xml'        => 'HTML/XML',
        'ini'        => 'INI',
        'dos'        => 'DOS/Batch',
        'pgsql'      => 'PostgreSQL',
    ];

    $build_label = static function(string $id) use ($label_map): string {
        if (isset($label_map[$id])) return $label_map[$id];
        $t = str_replace(['-','_'], ' ', $id);
        $t = ucwords($t);
        $t = preg_replace('/\bSql\b/i','SQL',$t);
        $t = preg_replace('/\bJson\b/i','JSON',$t);
        $t = preg_replace('/\bYaml\b/i','YAML',$t);
        $t = preg_replace('/\bXml\b/i','XML',$t);
        return $t;
    };

    // Build formats from highlight.php languages
    $geshiformats = ['markdown' => 'Markdown', 'text' => 'Plain Text'];
    foreach ($langs as $L) {
        $id = $L['id'];
        if ($id === 'plaintext') continue; // we already provide 'text'
        $geshiformats[$id] = $build_label($id);
    }

    // Popular band for the top of the select (tweak freely)
    $popular_formats = [
        'text','xml','css','javascript','json','yaml','php','python','sql','pgsql',
        'java','c','csharp','cpp','bash','markdown','go','ruby','rust','typescript','kotlin'
    ];

} else {
    // ---------- GeSHi formats (classic) ----------
    $geshiformats = [
        '4cs' => 'GADV 4CS',
        '6502acme' => 'ACME Cross Assembler',
        '6502kickass' => 'Kick Assembler',
        '6502tasm' => 'TASM/64TASS 1.46',
        '68000devpac' => 'HiSoft Devpac ST 2',
        'abap' => 'ABAP',
        'actionscript' => 'ActionScript',
        'actionscript3' => 'ActionScript 3',
        'ada' => 'Ada',
        'aimms' => 'AIMMS3',
        'algol68' => 'ALGOL 68',
        'apache' => 'Apache',
        'applescript' => 'AppleScript',
        'arm' => 'ARM Assembler',
        'asm' => 'ASM',
        'asp' => 'ASP',
        'asymptote' => 'Asymptote',
        'autoconf' => 'Autoconf',
        'autohotkey' => 'Autohotkey',
        'autoit' => 'AutoIt',
        'avisynth' => 'AviSynth',
        'awk' => 'Awk',
        'bascomavr' => 'BASCOM AVR',
        'bash' => 'BASH',
        'basic4gl' => 'Basic4GL',
        'bf' => 'Brainfuck',
        'bibtex' => 'BibTeX',
        'blitzbasic' => 'BlitzBasic',
        'bnf' => 'BNF',
        'boo' => 'Boo',
        'c' => 'C',
        'c_loadrunner' => 'C (LoadRunner)',
        'c_mac' => 'C for Macs',
        'c_winapi' => 'C (WinAPI)',
        'caddcl' => 'CAD DCL',
        'cadlisp' => 'CAD Lisp',
        'cfdg' => 'CFDG',
        'cfm' => 'ColdFusion',
        'chaiscript' => 'ChaiScript',
        'chapel' => 'Chapel',
        'cil' => 'CIL',
        'clojure' => 'Clojure',
        'cmake' => 'CMake',
        'cobol' => 'COBOL',
        'coffeescript' => 'CoffeeScript',
        'cpp' => 'C++',
        'cpp-qt' => 'C++ (with QT extensions)',
        'cpp-winapi' => 'C++ (WinAPI)',
        'csharp' => 'C#',
        'css' => 'CSS',
        'cuesheet' => 'Cuesheet',
        'd' => 'D',
        'dcl' => 'DCL',
        'dcpu16' => 'DCPU-16 Assembly',
        'dcs' => 'DCS',
        'delphi' => 'Delphi',
        'diff' => 'Diff-output',
        'div' => 'DIV',
        'dos' => 'DOS',
        'dot' => 'dot',
        'e' => 'E',
        'ecmascript' => 'ECMAScript',
        'eiffel' => 'Eiffel',
        'email' => 'eMail (mbox)',
        'epc' => 'EPC',
        'erlang' => 'Erlang',
        'euphoria' => 'Euphoria',
        'ezt' => 'EZT',
        'f1' => 'Formula One',
        'falcon' => 'Falcon',
        'fo' => 'FO (abas-ERP)',
        'fortran' => 'Fortran',
        'freebasic' => 'FreeBasic',
        'fsharp' => 'F#',
        'gambas' => 'GAMBAS',
        'gdb' => 'GDB',
        'genero' => 'Genero',
        'genie' => 'Genie',
        'gettext' => 'GNU Gettext',
        'glsl' => 'glSlang',
        'gml' => 'GML',
        'gnuplot' => 'GNUPlot',
        'go' => 'Go',
        'groovy' => 'Groovy',
        'gwbasic' => 'GwBasic',
        'haskell' => 'Haskell',
        'haxe' => 'Haxe',
        'hicest' => 'HicEst',
        'hq9plus' => 'HQ9+',
        'html4strict' => 'HTML 4.01',
        'html5' => 'HTML 5',
        'icon' => 'Icon',
        'idl' => 'Uno Idl',
        'ini' => 'INI',
        'inno' => 'Inno Script',
        'intercal' => 'INTERCAL',
        'io' => 'IO',
        'ispfpanel' => 'ISPF Panel',
        'j' => 'J',
        'java' => 'Java',
        'java5' => 'Java 5',
        'javascript' => 'JavaScript',
        'jcl' => 'JCL',
        'jquery' => 'jQuery',
        'kixtart' => 'KiXtart',
        'klonec' => 'KLone C',
        'klonecpp' => 'KLone C++',
        'latex' => 'LaTeX',
        'lb' => 'Liberty BASIC',
        'ldif' => 'LDIF',
        'lisp' => 'Lisp',
        'llvm' => 'LLVM',
        'locobasic' => 'Locomotive Basic',
        'logtalk' => 'Logtalk',
        'lolcode' => 'LOLcode',
        'lotusformulas' => 'Lotus Notes @Formulas',
        'lotusscript' => 'LotusScript',
        'lscript' => 'Lightwave Script',
        'lsl2' => 'Linden Script',
        'lua' => 'LUA',
        'm68k' => 'Motorola 68000 Assembler',
        'magiksf' => 'MagikSF',
        'make' => 'GNU make',
        'mapbasic' => 'MapBasic',
        'markdown' => 'Markdown',
        'matlab' => 'Matlab M',
        'mirc' => 'mIRC Scripting',
        'mmix' => 'MMIX',
        'modula2' => 'Modula-2',
        'modula3' => 'Modula-3',
        'mpasm' => 'Microchip Assembler',
        'mxml' => 'MXML',
        'mysql' => 'MySQL',
        'nagios' => 'Nagios',
        'netrexx' => 'NetRexx',
        'newlisp' => 'NewLisp',
        'nginx' => 'Nginx',
        'nsis' => 'NSIS',
        'oberon2' => 'Oberon-2',
        'objc' => 'Objective-C',
        'objeck' => 'Objeck',
        'ocaml' => 'Ocaml',
        'ocaml-brief' => 'OCaml (Brief)',
        'octave' => 'GNU/Octave',
        'oobas' => 'OpenOffice.org Basic',
        'oorexx' => 'ooRexx',
        'oracle11' => 'Oracle 11 SQL',
        'oracle8' => 'Oracle 8 SQL',
        'oxygene' => 'Oxygene (Delphi Prism)',
        'oz' => 'OZ',
        'parasail' => 'ParaSail',
        'parigp' => 'PARI/GP',
        'pascal' => 'Pascal',
        'pcre' => 'PCRE',
        'per' => 'Per (forms)',
        'perl' => 'Perl',
        'perl6' => 'Perl 6',
        'pf' => 'OpenBSD Packet Filter',
        'php' => 'PHP',
        'php-brief' => 'PHP (Brief)',
        'pic16' => 'PIC16 Assembler',
        'pike' => 'Pike',
        'pixelbender' => 'Pixel Bender',
        'pli' => 'PL/I',
        'plsql' => 'PL/SQL',
        'postgresql' => 'PostgreSQL',
        'povray' => 'POVRAY',
        'powerbuilder' => 'PowerBuilder',
        'powershell' => 'PowerShell',
        'proftpd' => 'ProFTPd config',
        'progress' => 'Progress',
        'prolog' => 'Prolog',
        'properties' => 'Properties',
        'providex' => 'ProvideX',
        'purebasic' => 'PureBasic',
        'pycon' => 'Python (console mode)',
        'pys60' => 'Python for S60',
        'python' => 'Python',
        'qbasic' => 'QuickBASIC',
        'racket' => 'Racket',
        'rails' => 'Ruby on Rails',
        'rbs' => 'RBScript',
        'rebol' => 'REBOL',
        'reg' => 'Microsoft REGEDIT',
        'rexx' => 'Rexx',
        'robots' => 'robots.txt',
        'rpmspec' => 'RPM Specification File',
        'rsplus' => 'R / S+',
        'ruby' => 'Ruby',
        'sas' => 'SAS',
        'scala' => 'Scala',
        'scheme' => 'Scheme',
        'scilab' => 'SciLab',
        'scl' => 'SCL',
        'sdlbasic' => 'sdlBasic',
        'smalltalk' => 'Smalltalk',
        'smarty' => 'Smarty',
        'spark' => 'SPARK',
        'sparql' => 'SPARQL',
        'sql' => 'SQL',
        'stonescript' => 'StoneScript',
        'systemverilog' => 'SystemVerilog',
        'tcl' => 'TCL',
        'teraterm' => 'Tera Term Macro',
        'text' => 'Plain Text',
        'thinbasic' => 'thinBasic',
        'tsql' => 'T-SQL',
        'typoscript' => 'TypoScript',
        'unicon' => 'Unicon',
        'upc' => 'UPC',
        'urbi' => 'Urbi',
        'unrealscript' => 'Unreal Script',
        'vala' => 'Vala',
        'vb' => 'Visual Basic',
        'vbnet' => 'VB.NET',
        'vbscript' => 'VB Script',
        'vedit' => 'Vedit Macro',
        'verilog' => 'Verilog',
        'vhdl' => 'VHDL',
        'vim' => 'Vim',
        'visualfoxpro' => 'Visual FoxPro',
        'visualprolog' => 'Visual Prolog',
        'whitespace' => 'Whitespace',
        'whois' => 'WHOIS (RPSL format)',
        'winbatch' => 'WinBatch',
        'xbasic' => 'XBasic',
        'xml' => 'XML',
        'xorg_conf' => 'Xorg Config',
        'xpp' => 'X++',
        'yaml' => 'YAML',
        'z80' => 'ZiLOG Z80 Assembler',
        'zxbasic' => 'ZXBasic'
    ];

    $popular_formats = [
        'text', 'html4strict', 'html5', 'css', 'javascript', 'php', 'perl',
        'python', 'postgresql', 'sql', 'xml', 'java', 'c', 'csharp', 'cpp', 'markdown'
    ];
}
